---
- name: Set timezone
  timezone:
    name: Europe/Moscow

### Network settings
- name: Remove default route
  lineinfile:
    line: "DEFROUTE=no"
    dest: /etc/sysconfig/network-scripts/ifcfg-enp0s3

- name: Add gateway
  lineinfile:
    line: "GATEWAY={{ hostvars['router']['ansible_host'] }}"
    dest: /etc/sysconfig/network-scripts/ifcfg-enp0s3
  notify:
    - restart network      

